travis:
  secure:
    BINSTAR_TOKEN: VbeQODLZU8hTjJVO6M1OHuEX5w2MOa11pb2ZPLoS1Gm+qtTakW2lJjSV8xVIEWcofKwJegoOCBXh0RoeN9jNZAcg9pjaoDe2desxqGLy1sxUih8b3uCd/SmJ+n9qHYknszRcmPkZ8k5EAIGedUxS1MmBWwGwmBPApOyvF6rDGCKEa+MgqdxlO0ZoaH8lXKB8HO95zvh6G/Cjnu6bMubIvMP6K4xpqtQJjEgIPGVlB0bfZSSDG9fSM1x3BxY/EsfLrKtssjxwO6KzL0F9/Dh+svZexR+VovOUEGesVpsNcXcHTg4v3q78wTYz1d+ECZE8kWi0/tsd72xkPMegx3SYovkJCapqvh1BPIH71JQTJwz+TIRu/WF9a/tLj1iXabpTbT8RNLZi57FsDeBbJqa//0i6vAiCg9tby4lMODGNLcp0IoYGHMLpWot333oy0T3VhsJA0lJlfG4U4gNXqQP4SBW0fzd7o8miLNmOVYlKaApJ37Fs1VmKOEmnKRivRwAY3BTSEzrOvtUphl79qUEiw7L777nhY+kkJGM9FNoM7pXnfzd2/oE1/7zfpXYjqIdUrbzWF2gdWc2Z+bGCvxyUl70JCN4A4Mqea33YyOUK0Slbp2E9GNatMq10TjyMqdq9iKJxkqXwEfRA6e0WqmOdFiD7z03bqo2b8pvyxP20jrU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
