travis:
  secure:
    BINSTAR_TOKEN: eI8HhF0hvqBG7qL1neIlEQ9NXaw1WVMDD9BPX8f0zirMF2EHSgvvgSDInORVh30Akym+ouXKwJVzuI7EEUPLFioVg+1gefxvcSm07f8e0TMFuedtc1y4rDjGU+/brk1xuMJYQzDKZZhjJ2UnsrWRAGZYJZgoVBmhbsOtwimk3lAifp0lon8q5cEGbUJGFn8M0oNZqwT/b3Wl/BR+hfVao/scbdNttZMUpHfHa8+/yeskyzXHUhkRzOBAfBCKc1W7LcP1J8MYrtv+uBsO4R7TskjC1qUpOYWuZVm28FscN5Wsbwg4qWbONcLKfk3yavc352+lxQdc8oxZskr2SIkweNtz4mxbDcwA3SdZzOtOp2d3Du9AKWeWMhmWOPCpWHN/GbIH0MpZ+to2CTx78Hy2TIONcDtIYGRxBhl+IGWdv1cn2j4VOzb1msVox9UcrF5d2tuCh0g12z4EgFH9WaCIKErQHKLT0yt8hYDHqPgHoOAlyXawNFlVwY3JYhIpze+KzBZFs5/Vat5tvsGsayJMFdAo5xDgvn3U8WVIUjyG0iMQFvNYjwT3qbOSX/gMcE6h2DPExsRFkGAozkzplqkdQGaye6Odn3nAIKMhrUJWz78T+dJ6HKsY6uqX2PfbC9LZ2eQJ6/Hy9gdaXzoG4IqBPglO1NLma5bwPPkXgL8EvRU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
